---
apiVersion: v1
kind: Service
metadata:
  name: searxng
spec:
  type: NodePort
  selector:
    app: searxng
  ports:
  - name: redis
    port: 6379
    targetPort: 6379
  - name: searxng
    port: 8889
    targetPort: 8080
  externalIPs:
  - 192.168.0.211
  - 192.168.0.221
  - 192.168.0.222
  - 192.168.0.223
  - 192.168.0.224
