---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: searxng
  labels:
    app: searxng
spec:
  replicas: 1
  selector:
    matchLabels:
      app: searxng
  template:
    metadata:
      labels:
        app: searxng
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: tpu
                operator: NotIn
                values:
                - "true"
      containers:
        - name: searxng
          image: docker.io/searxng/searxng:latest
#          image: searxng/searxng:2025.6.12-0b877f1 
          ports:
          - containerPort: 8080
            name: http
          env:
          - name: SEARXNG_BASE_URL
            value: "http://searxng.styxut.net"
          volumeMounts:
          - name: k8s-pv02
            mountPath: /etc/searxng
            subPath: searxng/etc/searxng
        - name: redis
#          image: docker.io/valkey/valkey:8-alpine
          image: docker.io/valkey/valkey:latest  
          command:
            - valkey-server
            - --save
            - "30"
            - "1"
            - --loglevel
            - warning
          ports:
          - containerPort: 6379
            name: redis
          resources:
            limits:
              cpu: 100m
              memory: 50Mi
          volumeMounts:
          - name: k8s-pv02
            mountPath: /var/lib/redis/data
            subPath: searxng/redis/data
      volumes:
      - name: k8s-pv02
        persistentVolumeClaim:
          claimName: synology-k8s-pv02 
